
package com.reservation.elibrary.proxy.reservations;

import java.util.List;
import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.3
 * Generated source version: 3.0
 * 
 */
@WebService(name = "Reservations", targetNamespace = "http://server.reservation.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Reservations {


    /**
     * 
     * @param arg0
     * @return
     *     returns com.reservation.elibrary.proxy.reservations.Reservation
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getReservation", targetNamespace = "http://server.reservation.org/", className = "com.reservation.elibrary.proxy.reservations.GetReservation")
    @ResponseWrapper(localName = "getReservationResponse", targetNamespace = "http://server.reservation.org/", className = "com.reservation.elibrary.proxy.reservations.GetReservationResponse")
    @Action(input = "http://server.reservation.org/Reservations/getReservationRequest", output = "http://server.reservation.org/Reservations/getReservationResponse")
    public Reservation getReservation(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @return
     *     returns java.util.List<com.reservation.elibrary.proxy.reservations.Reservation>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllReservations", targetNamespace = "http://server.reservation.org/", className = "com.reservation.elibrary.proxy.reservations.GetAllReservations")
    @ResponseWrapper(localName = "getAllReservationsResponse", targetNamespace = "http://server.reservation.org/", className = "com.reservation.elibrary.proxy.reservations.GetAllReservationsResponse")
    @Action(input = "http://server.reservation.org/Reservations/getAllReservationsRequest", output = "http://server.reservation.org/Reservations/getAllReservationsResponse")
    public List<Reservation> getAllReservations();

    /**
     * 
     * @param reservation
     * @return
     *     returns com.reservation.elibrary.proxy.reservations.Reservation
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addReservation", targetNamespace = "http://server.reservation.org/", className = "com.reservation.elibrary.proxy.reservations.AddReservation")
    @ResponseWrapper(localName = "addReservationResponse", targetNamespace = "http://server.reservation.org/", className = "com.reservation.elibrary.proxy.reservations.AddReservationResponse")
    @Action(input = "http://server.reservation.org/Reservations/addReservationRequest", output = "http://server.reservation.org/Reservations/addReservationResponse")
    public Reservation addReservation(
        @WebParam(name = "Reservation", targetNamespace = "")
        Reservation reservation);

}
